# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org'

platform :ios, '16.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'shared', :path => '../shared'
  pod 'GoogleSignIn'
end
