# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org'

platform :ios, '18.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'shared', :path => '../shared'
  pod 'ComposeApp', :path => '../composeApp'
  pod 'GoogleSignIn'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end
